name = "secureaiframeworks-cloud-v1"
compatibility_date = "2026-06-29"
workers_dev = false
preview_urls = false

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[routes]]
pattern = "secureaiframeworks.cloud"
custom_domain = true
